AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Favoulinks API Lambda Function

Globals:
  Function:
    Timeout: 5

Resources:
  FavoulinksDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: FavoulinksDB
      PrimaryKey:
        Name: url
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  FavoulinksRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,POST,GET,PUT,DELETE'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  FavoulinksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: favoulinks-function/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /favoulinks
            Method: ANY
            RestApiId: !Ref FavoulinksRestApi
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref FavoulinksDB

Outputs:
  FavoulinksRestApi:
    Description: "Favoulinks API Gateway endpoint URL for Prod stage "
    Value: !Sub "https://${FavoulinksRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/favoulinks/"
  FavoulinksFunction:
    Description: "Favoulinks Lambda Function ARN"
    Value: !GetAtt FavoulinksFunction.Arn
  FavoulinksDB:
    Description: "Favoulinks Dynamic Database ARN"
    Value: !GetAtt FavoulinksDB.Arn